name: git-hub

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-gh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: saltball
        password: "${{ secrets.GITHUB_TOKEN }}"  # you don't need to manually set this secret. GitHub does it on your behalf
        registry: docker.pkg.github.com
        image_name: dpmd_lmp_docker